Updated libXC to latest release

diff --git a/external/libXC/testsuite/xc-run_testsuite b/external/libXC/testsuite/xc-run_testsuite
--- a/external/libXC/testsuite/xc-run_testsuite
+++ b/external/libXC/testsuite/xc-run_testsuite
@@ -1,49 +1,97 @@
 #!/usr/bin/env bash
-# $Id:  $
+
+## This Source Code Form is subject to the terms of the Mozilla Public
+## License, v. 2.0. If a copy of the MPL was not distributed with this
+## file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
 if [ -n "$SKIP_CHECK" ]; then
-    echo "Skipping checks"
-    exit 0
+  echo "Skipping checks"
+  exit 0
 fi
 
 if [ -z "$srcdir" ]; then
   srcdir="./"
 fi
 
+if [ -z "$tmpdir" ]; then
+  tmpdir="/tmp"
+fi
+
 if [ -z "$builddir" ]; then
   builddir="./"
 fi
 
-ok=0
-echo -e "\033[33;1mComparing against reference data\033[0m"
-for i in `ls $srcdir/regression/*.data.bz2 | sort`; do
-  bunzip2 -c $i >/tmp/$$.data_ref
+# We only print using colors if the output is going to a terminal
+if [ -t 1 ] ; then
+  NC='\033[0m'
+  RED='\033[1;31m'
+  GREEN='\033[1;32m'
+  YELLOW='\033[1;33m'
+  PINK='\033[1;35m'
+fi
 
-  func=`basename $i .data.bz2`
-  fname=`printf '%-30s' $func`
-  echo -ne "\033[0m :: Testing \033[35;1m$fname"
-  $builddir/xc-regression $func >/tmp/$$data_test
+workdir=$(mktemp -d ${tmpdir}/libxc.XXXXXXXXXX)
 
-  res=`diff -q /tmp/$$.data_ref /tmp/$$data_test`
-  if [ "x$res" = "x" ]; then
-    echo -e "\033[32;1mOK"
-  else
-    echo -e "\033[31;1mFAIL"
-    ok=$((ok + 1));
-  fi
+fail=0
+echo -e "${YELLOW}Comparing against reference data${NC}"
+echo -e "Using ${workdir} as working directory"
+echo -e "========================================================================="
+echo -e "   Functional                    System      NSpin   Quantity    Result"
+echo -e "========================================================================="
+
+if [ "z$1" != "z" ]; then
+  selfunc="${1}.*.bz2"
+else
+  selfunc="*.bz2"
+fi
+
+for dir in $(ls -d $srcdir/regression/*); do
+  for i in $(ls $dir/$selfunc 2> /dev/null | LANG=C sort); do
+    refname=$(basename ${i} .bz2)
+    func=${refname%%.*}
+    #if [ $func != "gga_x_wpbeh" ]; then
+    #  continue
+    #fi
+    testcase=${refname#*.}
+    system=${testcase%%.*}
+    order=${testcase##*.}
+    if [ "x${testcase#*.}" = "xunpol.$order" ]; then
+      nspin=1
+    else
+      nspin=2
+    fi
+    case $order in
+    0)
+      label=exc
+      tol=5e-8
+      ;;
+    1)
+      label=vxc
+      tol=5e-5
+      ;;
+    2)
+      label=fxc
+      tol=5e-4
+      ;;
+    esac
+    name=$(printf '%-30s %-12s %-8d %-5s' ${func} ${system} ${nspin} ${label})
+  
+    echo -ne "${NC} * ${PINK}${name}"
+
+    bunzip2 -c $dir/$refname.bz2 > $workdir/${refname}_ref
+
+    $EXEC $builddir/xc-regression $func $nspin $order $srcdir/input/$system $workdir/$refname > /dev/null
+  
+    res=$($builddir/xc-error $workdir/$refname $workdir/${refname}_ref $tol)
+    if [ "x$res" = "x1" ]; then
+      echo -e "      ${GREEN}OK"
+      rm $workdir/$refname $workdir/${refname}_ref
+    else
+      echo -e "     ${RED}FAIL"
+      let fail++
+    fi
+  done
 done
-echo -e "\033[0m"
+echo -e "${NC}"
 
-exit $ok
-
-#echo -e "\033[33;1mInternal consistency\033[0m"
-#for i in `grep -E 'XC_LDA|XC_GGA' $srcdir/../src/xc_funcs.h | awk '{printf("%s,%d\n",$2, $3)}'`; do
-#  func=`echo $i|sed 's/,.*//'`;
-#  number=`echo $i|sed 's/.*,//'`;
-#
-#  if [ $number -ne 6 -a $number -ne 160 ]; then
-#    echo -e "\033[0m :: Testing \033[32;1m$func\033[0m ($number)"
-#    ./xc-consistency $number
-#  fi
-#  echo
-#done
+exit $fail
